--OMOP v5.3.1 extraction code for N3C
--Written by Kristin Kostka, OHDSI
--Code written for Oracle
--This extract purposefully excludes the following OMOP tables: PERSON, OBSERVATION_PERIOD, VISIT_OCCURRENCE, CONDITION_OCCURRENCE, DRUG_EXPOSURE, PROCEDURE_OCCURRENCE, MEASUREMENT, OBSERVATION, LOCATION, CARE_SITE, PROVIDER,
--Currently this script extracts the derived tables for DRUG_ERA, DOSE_ERA, CONDITION_ERA as well (could be modified we run these in Palantir instead)
--Assumptions: 
--	1. You have already built the N3C_COHORT table (with that name) prior to running this extract
--	2. You are extracting data with a lookback period to 1-1-2018

-- To run, you will need to find and replace @cdm_database_schema with your local OMOP schema details

--PERSON
--OUTPUT_FILE: PERSON.csv
SELECT
   PERSON_ID,
   GENDER_CONCEPT_ID,
   YEAR_OF_BIRTH,
   MONTH_OF_BIRTH,
   RACE_CONCEPT_ID,
   ETHNICITY_CONCEPT_ID,
   LOCATION_ID,
   PROVIDER_ID,
   CARE_SITE_ID,
   PERSON_SOURCE_VALUE,
   GENDER_SOURCE_VALUE,
   RACE_SOURCE_VALUE,
   RACE_SOURCE_CONCPT_ID,
   ETHNICITY_SOURCE_VALUE,
   ETHNICITY_SOURCE_CONCEPT_ID,
  FROM @cdm_database_schema.PERSON p JOIN @cdm_database_schema.N3C_COHORT n ON p.PERSON.PERSON_ID = n.N3C_COHORT.PERSON_ID;

--OBSERVATION_PERIOD
--OUTPUT_FILE: OBSERVATION_PERIOD.csv
SELECT
   OBSERVATION_PERIOD_ID,
   PERSON_ID,
   TO_CHAR(OBSERVATION_PERIOD_START_DATE, 'YYYY-MM-DD HH24:MI:SS') as OBSERVATION_PERIOD_START_DATE,
   TO_CHAR(OBSERVATION_PERIOD_END_DATE, 'YYYY-MM-DD HH24:MI:SS') as OBSERVATION_PERIOD_END_DATE,
   PERIOD_TYPE_CONCEPT_ID,
 FROM @cdm_database_schema.OBSERVATION_PERIOD p JOIN @cdm_database_schema.N3C_COHORT n ON p.PERSON_ID = n.PERSON_ID;
 
--VISIT_OCCURRENCE
--OUTPUT_FILE: VISIT_OCCURRENCE.csv
SELECT
   VISIT_OCCURRENCE_ID,
   PERSON_ID,
   VISIT_CONCEPT_ID,
   TO_CHAR(VISIT_START_DATE, 'YYYY-MM-DD HH24:MI:SS') as VISIT_START_DATE,
   TO_CHAR(VISIT_START_DATETIME, 'YYYY-MM-DD HH24:MI:SS') as VISIT_START_DATETIME,
   TO_CHAR(VISIT_END_DATE, 'YYYY-MM-DD HH24:MI:SS') as VISIT_END_DATE,
   TO_CHAR(VISIT_END_DATETIME, 'YYYY-MM-DD HH24:MI:SS') as VISIT_END_DATETIME,
   VISIT_TYPE_CONCEPT_ID,
   PROVIDER_ID,
   CARE_SITE_ID,
   VISIT_SOURCE_VALUE,
   VISIT_SOURCE_CONCEPT_ID,
   ADMITTING_SOURCE_CONCEPT_ID,
   ADMITTING_SOURCE_VALUE,
   DISCHARGE_TO_CONCEPT_ID,
   DISCHARGE_TO_SOURCE_VALUE,
   PRECEDING_VISIT_OCCURRENCE_ID,
FROM @cdm_database_schema.VISIT_OCCURRENCE v JOIN N3C_COHORT n ON v.PERSON_ID = n.PERSON_ID
WHERE VISIT_START_DATE >= '01-JAN-2018';

--CONDITION_OCCURRENCE
--OUTPUT_FILE: CONDITION_OCCURRENCE.csv
SELECT
   CONDITION_OCCURRENCE_ID,
   PERSON_ID,
   CONDITION_CONCEPT_ID,
   TO_CHAR(CONDITION_START_DATE, 'YYYY-MM-DD HH24:MI:SS') as CONDITION_START_DATE,
   TO_CHAR(CONDITION_START_DATETIME, 'YYYY-MM-DD HH24:MI:SS') as CONDITION_START_DATETIME,
   TO_CHAR(CONDITION_END_DATE, 'YYYY-MM-DD HH24:MI:SS') as CONDITION_END_DATE,
   TO_CHAR(CONDITON_END_DATETIME, 'YYYY-MM-DD HH24:MI:SS') as CONDITION_END_DATETIME,
   CONDITION_TYPE_CONCEPT_ID,
   CONDITION_STATUS_CONCEPT_ID,
   STOP_REASON,
   VISIT_OCCURRENCE_ID,
   VISIT_DETAIL_ID,
   CONDITION_SOURCE_VALUE,
   CONDITION_SOURCE_CONCEPT_ID,
   CONDITON_STATUS_SOURCE_VALUE,
FROM @cdm_database_schema.CONDITION_OCCURRENCE co JOIN N3C_COHORT n ON CO.person_id = n.person_id
WHERE REPORT_DATE >= '01-JAN-2018';

--DRUG_EXPOSURE
--OUTPUT_FILE: DRUG_EXPOSURE.csv
SELECT
   DRUG_EXPOSURE_ID,
   PERSON_ID,
   DRUG_CONCEPT_ID,
   TO_CHAR(DRUG_EXPOSURE_START_DATE, 'YYYY-MM-DD HH24:MI:SS') as DRUG_EXPOSURE_START_DATE,
   TO CHAR(DRUG_EXPOSURE_START_DATETIME, 'YYYY-MM-DD HH24:MI:SS') as DRUG_EXPOSURE_START_DATETIME,
   TO CHAR(DRUG_EXPOSURE_END_DATE, 'YYYY-MM-DD HH24:MI:SS') as DRUG_EXPOSURE_END_DATE,
   TO CHAR(DRUG_EXPOSURE_END_DATETIME, 'YYYY-MM-DD HH24:MI:SS') as DRUG_EXPOSURE_END_DATETIME,
   DRUG_TYPE_CONCEPT_ID,
   STOP_REASON,
   REFILLS,
   QUANTITY,
   DAYS_SUPPLY,
   SIG,
   ROUTE_CONCEPT_ID,
   LOT_NUMBER,
   PROVIDER_ID,
   VISIT_OCCURRENCE_ID,
   VISIT_DETAIL_ID,
   DRUG_SOURCE_VALUE,
   DRUG_SOURCE_CONCEPT_ID,
   ROUTE_SOURCE_VALUE,
   DOSE_UNIT_SOURCE_VALUE,
FROM @cdm_database_schema.DRUG_EXPOSURE de JOIN N3C_COHORT n ON de.PERSON_ID = n.PERSON_ID
WHERE DRUG_EXPOSURE_START_DATE >= '01-JAN-2018';

--PROCEDURE_OCCURRENCE
--OUTPUT_FILE: PROCEDURE_OCCURRENCE.csv
SELECT
   PROCEDURE_OCCURRENCE_ID,
   PERSON_ID,
   PROCEDURE_CONCEPT_ID,
   TO_CHAR(PROCEDURE_DATE, 'YYYY-MM-DD HH24:MI:SS') as PROCEDURE_DATE,
   TO_CHAR(PROCEDURE_DATETIME, 'YYYY-MM-DD HH24:MI:SS') as PROCEDURE_DATETIME,
   PROCEDURE_TYPE_CONCEPT_ID,
   MODIFIER_CONCEPT_ID,
   QUANTITY,
   PROVIDER_ID,
   VISIT_OCCURRENCE_ID,
   VISIT_DETAIL_ID,
   PROCEDURE_SOURCE_VALUE,
   PROCEDURE_SOURCE_CONCEPT_ID,
   MODIFIER_SOURCE_VALUE
FROM @cdm_database_schema.PROCEDURE_OCCURRENCE po JOIN N3C_COHORT n ON PO.PERSON_ID = N.PERSON_ID
WHERE PROCEDURE_DATE >= '01-JAN-2018';

--MEASUREMENT
--OUTPUT_FILE: MEASUREMENT.csv
SELECT
   MEASUREMENT_ID,
   PERSON_ID,
   MEASUREMENT_CONCEPT_ID,
   TO_CHAR(MEASUREMENT_DATE, 'YYYY-MM-DD HH24:MI:SS') as MEASUREMENT_DATE,
   TO_CHAR(MEASUREMENT_DATETIME, 'YYYY-MM-DD HH24:MI:SS') as MEASUREMENT_DATETIME,
   MEASUREMENT_TIME,
   MEASUREMENT_TYPE_CONCEPT_ID,
   OPERATOR_CONCEPT_ID,
   VALUE_AS_NUMBER,
   VALUE_AS_CONCEPT_ID,
   UNIT_CONCEPT_ID,
   RANGE_LOW,
   RANGE_HIGH,
   PROVIDER_ID,
   VISIT_OCCURRENCE_ID,
   VISIT_DETAIL_ID,
   MEASUREMENT_SOURCE_VALUE,
   MEASUREMENT_SOURCE_CONCEPT_ID,
   UNIT_SOURCE_VALUE,
   VALUE_SOURCE_VALUE
FROM @cdm_database_schema.MEASURMENT m JOIN N3C_COHORT n ON M.PERSON_ID = N.PERSON_ID
WHERE MEASUREMENT_DATE >= '01-JAN-2018';

--OBSERVATION
--OUTPUT_FILE: OBSERVATION.csv
SELECT
   OBSERVATION_ID,
   PERSON_ID,
   OBSERVATION_CONCEPT_ID,
   TO_CHAR(OBSERVATION_DATE, 'YYYY-MM-DD HH24:MI:SS') as OBSERVATION_DATE,
   TO_CHAR(OBSERVATION_DATETIME, 'YYYY-MM-DD HH24:MI:SS') as OBSERVATION_DATETIME,
   OBSERVATION_TYPE_CONCEPT_ID,
   VALUE_AS_NUMBER,
   VALUE_AS_STRING,
   VALUE_AS_CONCEPT_ID,
   QUALIFIER_CONCEPT_ID,
   UNIT_CONCEPT_ID,
   PROVIDER_ID,
   VISIT_OCCURRENCE_ID,
   VISIT_DETAIL_ID,
   OBSERVATION_SOURCE_VALUE,
   OBSERVATION_SOURCE_CONCEPT_ID,
   UNIT_SOURCE_VALUE,
   QUALIFIER_SOURCE_VALUE
FROM @cdm_database_schema.OBSERVATION o JOIN N3C_COHORT n ON O.PERSON_ID = N.PERSON_ID
WHERE OBSERVATION_DATE >= '01-JAN-2018';

--LOCATION
--OUTPUT_FILE: LOCATION.csv
SELECT
   LOCATION_ID,
   null as ADDRESS_1, -- to avoid identifying information
   null as ADDRESS_2, -- to avoid identifying information
   CITY,
   STATE,
   ZIP,
   COUNTY,
   LOCATION_SOURCE_VALUE,
FROM @cdm_database_schema.LOCATION;

--CARE_SITE
--OUTPUT_FILE: CARE_SITE.csv
SELECT
   CARE_SITE_ID,
   CARE_SITE_NAME,
   PLACE_OF_SERVICE_CONCEPT_ID,
   LOCATION_ID,
   CARE_SITE_SOURCE_VALUE,
   PLACE_OF_SERVICE_SOURCE_VALUE,  
FROM @cdm_database_schema.CARE_SITE;

--PROVIDER
--OUTPUT_FILE: PROVIDER.csv
SELECT
   PROVIDER_ID,
   null as PROVIDER_NAME, -- to avoid accidentally identifying sites
   null as NPI, -- to avoid accidentally identifying sites
   null as DEA, -- to avoid accidentally identifying sites
   SPECIALTY_CONCEPT_ID,
   CARE_SITE_ID,
   null as YEAR_OF_BIRTH,
   GENDER_CONCEPT_ID,
   null as PROVIDER_SOURCE_VALUE, -- to avoid accidentally identifying sites
   SPECIALTY_SOURCE_VALUE,
   SPECIALTY_SOURCE_CONCEPT_ID,
   GENDER_SOURCE_VALUE,
   GENDER_SOURCE_CONCEPT_ID
FROM @cdm_database_schema.PROVIDER;
 
--Note: it has yet to be decided if Era tables will be constructured downstream in Palantir platform.
-- If it is decided that eras will be reconstructed, these three tables will be omitted.
 
--DRUG_ERA
--OUTPUT_FILE: DRUG_ERA.csv
SELECT
   DRUG_ERA_ID,
   PERSON_ID,
   DRUG_CONCEPT_ID,
   TO_CHAR(DRUG_ERA_START_DATE, 'YYYY-MM-DD HH24:MI:SS') as DRUG_ERA_START_DATE,
   TO_CHAR(DRUG_ERA_END_DATE, 'YYYY-MM-DD HH24:MI:SS') as DRUG_ERA_END_DATE,   
   DRUG_EXPOSURE_COUNT,
   GAP_DAYS
FROM @cdm_database_schema.DRUG_ERA dre JOIN N3C_COHORT n ON DRE.PERSON_ID = N.PERSON_ID
WHERE DRUG_ERA_START_DATE >= '01-JAN-2018';

--DOSE_ERA
--OUTPUT_FILE: DOSE_ERA.csv
SELECT
   DOSE_ERA_ID,
   PERSON_ID,
   DRUG_CONCEPT_ID,
   UNIT_CONCEPT_ID,
   DOSE_VALUE,
   TO_CHAR(DOSE_ERA_START_DATE, 'YYYY-MM-DD HH24:MI:SS') as DOSE_ERA_START_DATE,
   TO_CHAR(DOSE_ERA_END_DATE, 'YYYY-MM-DD HH24:MI:SS') as DOSE_ERA_END_DATE,   
FROM @cdm_database_schema.DOSE_ERA do JOIN N3C_COHORT n ON DO.PERSON_ID = N.PERSON_ID
WHERE DOSE_ERA_START_DATE >= '01-JAN-2018';

--CONDITION_ERA
--OUTPUT_FILE: CONDITION_ERA.csv
SELECT
   CONDITION_ERA_ID,
   PERSON_ID,
   CONDITION_CONCEPT_ID,
   TO_CHAR(CONDITON_ERA_START_DATE, 'YYYY-MM-DD HH24:MI:SS') as CONDITION_ERA_START_DATE,
   TO_CHAR(CONDITION_ERA_END_DATE, 'YYYY-MM-DD HH24:MI:SS') as CONDITION_ERA_END_DATE,   
   CONDITION_OCCURRENCE_COUNT
FROM @cdm_database_schema.CONDITION_ERA ce JOIN N3C_COHORT n ON CE.PERSON_ID = N.PERSON_ID
WHERE CONDITION_ERA_START_DATE >= '01-JAN-2018';

--DATA_COUNTS TABLE
--OUTPUT_FILE: DATA_COUNTS.csv
SELECT * from
(select 
   'PERSON' as TABLE_NAME, 
   (select count(*) from PERSON JOIN N3C_COHORT ON PERSON.PERSON_ID = N3C_COHORT.PERSON_ID) as ROW_COUNT
from DUAL

UNION

select 
   'OBSERVATION_PERIOD' as TABLE_NAME,
   (select count(*) from OBSERVATION_PERIOD JOIN N3C_COHORT ON OBSERVATION_PERIOD.PERSON_ID = N3C_COHORT.PERSON_ID AND OBSERVATION_PERIOD_START_DATE >= '01-JAN-2018') as ROW_COUNT
from DUAL

UNION

select 
   'VISIT_OCCURRENCE' as TABLE_NAME,
   (select count(*) from VISIT_OCCURRENCE JOIN N3C_COHORT ON VISIT_OCCURRENCE.PERSON_ID = N3C_COHORT.PERSON_ID AND VISIT_START_DATE >= '01-JAN-2018') as ROW_COUNT
from DUAL

UNION

select 
   'CONDITION_OCCURRENCE' as TABLE_NAME,
   (select count(*) from CONDITION_OCCURRENCE JOIN N3C_COHORT ON CONDITION_OCCURRENCE.PERSON_ID = N3C_COHORT.PERSON_ID AND CONDITION_START_DATE >= '01-JAN-2018') as ROW_COUNT
from DUAL

UNION

select 
   'DRUG_EXPOSURE' as TABLE_NAME,
   (select count(*) from DRUG_EXPOSURE JOIN N3C_COHORT ON DRUG_EXPOSURE.PERSON_ID = N3C_COHORT.PERSON_ID AND DRUG_EXPOSURE_START_DATE >= '01-JAN-2018') as ROW_COUNT
from DUAL

UNION

select 
   'PROCEDURE_OCCURRENCE' as TABLE_NAME,
   (select count(*) from PROCEDURE_OCCURRENCE JOIN N3C_COHORT ON PROCEDURE_OCCURRENCE.PERSON_ID = N3C_COHORT.PERSON_ID AND PROCEDURE_DATE >= '01-JAN-2018') as ROW_COUNT
from DUAL

UNION
   
select 
   'MEASUREMENT' as TABLE_NAME,
   (select count(*) from MEASUREMENT JOIN N3C_COHORT ON MEASUREMENT.PERSON_ID = N3C_COHORT.PERSON_ID AND MEASUREMENT_DATE >= '01-JAN-2018') as ROW_COUNT
from DUAL

UNION

select 
   'OBSERVATION' as TABLE_NAME,
   (select count(*) from OBSERVATION JOIN N3C_COHORT ON OBSERVATION.PERSON_ID = N3C_COHORT.PERSON_ID AND OBSERVATION_DATE >= '01-JAN-2018') as ROW_COUNT
from DUAL

UNION

--OMOP does not have PERSON_ID for Location, Care Site and Provider tables so we need to determine the applicability of this check
--We could re-engineer the cohort table to include the JOIN variables
select 
   'LOCATION' as TABLE_NAME,
   (select count(*) from LOCATION) as ROW_COUNT
from DUAL

UNION

select 
   'CARE_SITE' as TABLE_NAME,
   (select count(*) from CARE_SITE) as ROW_COUNT
from DUAL

UNION
 
 select 
   'PROVIDER' as TABLE_NAME,
   (select count(*) from PROVIDER) as ROW_COUNT
from DUAL

UNION

select 
   'DRUG_ERA' as TABLE_NAME,
   (select count(*) from DRUG_ERA JOIN N3C_COHORT ON DRUG_ERA.PERSON_ID = N3C_COHORT.PERSON_ID AND DRUG_ERA_START_DATE >= '01-JAN-2018') as ROW_COUNT
from DUAL

UNION

select 
   'DOSE_ERA' as TABLE_NAME,
   (select count(*) from DOSE_ERA JOIN N3C_COHORT ON DOSE_ERA.PERSON_ID = N3C_COHORT.PERSON_ID AND DOSE_ERA_START_DATE >= '01-JAN-2018') as ROW_COUNT
from DUAL

UNION

select 
   'CONDITION_ERA' as TABLE_NAME,
   (select count(*) from CONDITION_ERA JOIN N3C_COHORT ON CONDITION_ERA.PERSON_ID = N3C_COHORT.PERSON_ID AND CONDITION_ERA_START_DATE >= '01-JAN-2018') as ROW_COUNT
from DUAL);

--MANIFEST TABLE: CHANGE PER YOUR SITE'S SPECS
--OUTPUT_FILE: MANIFEST.csv
select
   'OHDSI' as SITE_ABBREV,
   'Jane Doe' as CONTACT_NAME,
   'jane_doe@OHDSI.edu' as CONTACT_EMAIL,
   'OMOP' as CDM_NAME,
   '5.3.1' as CDM_VERSION,
   'Y' as N3C_PHENOTYPE_YN,
   '1.3' as N3C_PHENOTYPE_VERSION,
   TO_CHAR(sysdate, 'YYYY-MM-DD HH24:MI:SS') as RUN_DATE,
   TO_CHAR(sysdate -2, 'YYYY-MM-DD HH24:MI:SS') as UPDATE_DATE,		--change integer based on your site's data latency
   TO_CHAR(sysdate +3, 'YYYY-MM-DD HH24:MI:SS') as NEXT_SUBMISSION_DATE					--change integer based on your site's load frequency
from dual;
