--PCORNet 5.1 extraction code for N3C
--Written by Emily Pfaff, UNC Chapel Hill
--Code written for Oracle
--This extract purposefully excludes the following PCORnet tables: ENROLLMENT, HARVEST, HASH_TOKEN, PCORNET_TRIAL
--Assumptions: 
--	1. You have already built the N3C_COHORT table (with that name) prior to running this extract
--	2. You are extracting data with a lookback period of 2 years

--DEMOGRAPHIC
SELECT
   DEMOGRAPHIC.PATID,
   BIRTH_DATE,
   BIRTH_TIME,
   SEX,
   SEXUAL_ORIENTATION,
   GENDER_IDENTITY,
   HISPANIC,
   RACE,
   BIOBANK_FLAG,
   PAT_PREF_LANGUAGE_SPOKEN,
   RAW_SEX,
   RAW_SEXUAL_ORIENTATION,
   RAW_GENDER_IDENTITY,
   RAW_HISPANIC,
   RAW_RACE,
   RAW_PAT_PREF_LANGUAGE_SPOKEN 
FROM DEMOGRAPHIC JOIN N3C_COHORT ON DEMOGRAPHIC.PATID = N3C_COHORT.PATID;

--ENCOUNTER
SELECT
   ENCOUNTERID,
   ENCOUNTER.PATID,
   ADMIT_DATE,
   ADMIT_TIME,
   DISCHARGE_DATE,
   DISCHARGE_TIME,
   PROVIDERID,
   FACILITY_LOCATION,
   ENC_TYPE,
   FACILITYID,
   DISCHARGE_DISPOSITION,
   DISCHARGE_STATUS,
   DRG,
   DRG_TYPE,
   ADMITTING_SOURCE,
   PAYER_TYPE_PRIMARY,
   PAYER_TYPE_SECONDARY,
   FACILITY_TYPE,
   RAW_SITEID,
   RAW_ENC_TYPE,
   RAW_DISCHARGE_DISPOSITION,
   RAW_DISCHARGE_STATUS,
   RAW_DRG_TYPE,
   RAW_ADMITTING_SOURCE,
   RAW_FACILITY_TYPE,
   RAW_PAYER_TYPE_PRIMARY,
   RAW_PAYER_NAME_PRIMARY,
   RAW_PAYER_ID_PRIMARY,
   RAW_PAYER_TYPE_SECONDARY,
   RAW_PAYER_NAME_SECONDARY,
   RAW_PAYER_ID_SECONDARY 
FROM ENCOUNTER JOIN N3C_COHORT ON ENCOUNTER.PATID = N3C_COHORT.PATID
WHERE ADMIT_DATE >= ADD_MONTHS(SYSDATE, -24);

--CONDITION
SELECT
   CONDITIONID,
   CONDITION.PATID,
   ENCOUNTERID,
   REPORT_DATE,
   RESOLVE_DATE,
   ONSET_DATE,
   CONDITION_STATUS,
   CONDITION,
   CONDITION_TYPE,
   CONDITION_SOURCE,
   RAW_CONDITION_STATUS,
   RAW_CONDITION,
   RAW_CONDITION_TYPE,
   RAW_CONDITION_SOURCE 
FROM CONDITION JOIN N3C_COHORT ON CONDITION.PATID = N3C_COHORT.PATID
WHERE REPORT_DATE >= ADD_MONTHS(SYSDATE, -24);

--DEATH
--No lookback period for death
SELECT
   DEATH.PATID,
   DEATH_DATE,
   DEATH_DATE_IMPUTE,
   DEATH_SOURCE,
   DEATH_MATCH_CONFIDENCE 
FROM DEATH JOIN N3C_COHORT ON DEATH.PATID = N3C_COHORT.PATID;

--DEATH CAUSE
--No lookback period for death cause
SELECT
   DEATH_CAUSE.PATID,
   DEATH_CAUSE,
   DEATH_CAUSE_CODE,
   DEATH_CAUSE_TYPE,
   DEATH_CAUSE_SOURCE,
   DEATH_CAUSE_CONFIDENCE 
FROM DEATH_CAUSE JOIN N3C_COHORT ON DEATH_CAUSE.PATID = N3C_COHORT.PATID;

--DIAGNOSIS
SELECT
   DIAGNOSISID,
   DIAGNOSIS.PATID,
   ENCOUNTERID,
   ENC_TYPE,
   ADMIT_DATE,
   PROVIDERID,
   DX,
   DX_TYPE,
   DX_DATE,
   DX_SOURCE,
   DX_ORIGIN,
   PDX,
   DX_POA,
   RAW_DX,
   RAW_DX_TYPE,
   RAW_DX_SOURCE,
   RAW_PDX,
   RAW_DX_POA 
FROM DIAGNOSIS JOIN N3C_COHORT ON DIAGNOSIS.PATID = N3C_COHORT.PATID
WHERE DX_DATE >= ADD_MONTHS(SYSDATE, -24);

--DISPENSING
SELECT
   DISPENSINGID,
   DISPENSING.PATID,
   PRESCRIBINGID,
   DISPENSE_DATE,
   NDC,
   DISPENSE_SOURCE,
   DISPENSE_SUP,
   DISPENSE_AMT,
   DISPENSE_DOSE_DISP,
   DISPENSE_DOSE_DISP_UNIT,
   DISPENSE_ROUTE,
   RAW_NDC,
   RAW_DISPENSE_DOSE_DISP,
   RAW_DISPENSE_DOSE_DISP_UNIT,
   RAW_DISPENSE_ROUTE 
FROM DISPENSING JOIN N3C_COHORT ON DISPENSING.PATID = N3C_COHORT.PATID
WHERE DISPENSE_DATE >= ADD_MONTHS(SYSDATE, -24);

--IMMUNIZATION
--No lookback period for immunizations
SELECT
   IMMUNIZATIONID,
   IMMUNIZATION.PATID,
   ENCOUNTERID,
   PROCEDURESID,
   VX_PROVIDERID,
   VX_RECORD_DATE,
   VX_ADMIN_DATE,
   VX_CODE_TYPE,
   VX_CODE,
   VX_STATUS,
   VX_STATUS_REASON,
   VX_SOURCE,
   VX_DOSE,
   VX_DOSE_UNIT,
   VX_ROUTE,
   VX_BODY_SITE,
   VX_MANUFACTURER,
   VX_LOT_NUM,
   VX_EXP_DATE,
   RAW_VX_NAME,
   RAW_VX_CODE,
   RAW_VX_CODE_TYPE,
   RAW_VX_DOSE,
   RAW_VX_DOSE_UNIT,
   RAW_VX_ROUTE,
   RAW_VX_BODY_SITE,
   RAW_VX_STATUS,
   RAW_VX_STATUS_REASON,
   RAW_VX_MANUFACTURER 
FROM IMMUNIZATION JOIN N3C_COHORT ON IMMUNIZATION.PATID = N3C_COHORT.PATID;

--LAB_RESULT_CM
SELECT
   LAB_RESULT_CM_ID,
   LAB_RESULT_CM.PATID,
   ENCOUNTERID,
   SPECIMEN_SOURCE,
   LAB_LOINC,
   LAB_RESULT_SOURCE,
   LAB_LOINC_SOURCE,
   PRIORITY,
   RESULT_LOC,
   LAB_PX,
   LAB_PX_TYPE,
   LAB_ORDER_DATE,
   SPECIMEN_DATE,
   SPECIMEN_TIME,
   RESULT_DATE,
   RESULT_TIME,
   RESULT_QUAL,
   RESULT_SNOMED,
   RESULT_NUM,
   RESULT_MODIFIER,
   RESULT_UNIT,
   NORM_RANGE_LOW,
   NORM_MODIFIER_LOW,
   NORM_RANGE_HIGH,
   NORM_MODIFIER_HIGH,
   ABN_IND,
   RAW_LAB_NAME,
   RAW_LAB_CODE,
   RAW_PANEL,
   RAW_RESULT,
   RAW_UNIT,
   RAW_ORDER_DEPT,
   RAW_FACILITY_CODE 
FROM LAB_RESULT_CM JOIN N3C_COHORT ON LAB_RESULT_CM.PATID = N3C_COHORT.PATID
WHERE LAB_ORDER_DATE >= ADD_MONTHS(SYSDATE, -24);

--LDS_ADDRESS_HISTORY
SELECT
   ADDRESSID,
   LDS_ADDRESS_HISTORY.PATID,
   ADDRESS_USE,
   ADDRESS_TYPE,
   ADDRESS_PREFERRED,
   ADDRESS_CITY,
   ADDRESS_STATE,
   ADDRESS_ZIP5,
   ADDRESS_ZIP9,
   ADDRESS_PERIOD_START,
   ADDRESS_PERIOD_END 
FROM LDS_ADDRESS_HISTORY JOIN N3C_COHORT ON LDS_ADDRESS_HISTORY.PATID = N3C_COHORT.PATID
WHERE ADDRESS_PERIOD_END is null OR ADDRESS_PERIOD_END >= ADD_MONTHS(SYSDATE, -24);

--MED_ADMIN
SELECT
   MEDADMINID,
   MED_ADMIN.PATID,
   ENCOUNTERID,
   PRESCRIBINGID,
   MEDADMIN_PROVIDERID,
   MEDADMIN_START_DATE,
   MEDADMIN_START_TIME,
   MEDADMIN_STOP_DATE,
   MEDADMIN_STOP_TIME,
   MEDADMIN_TYPE,
   MEDADMIN_CODE,
   MEDADMIN_DOSE_ADMIN,
   MEDADMIN_DOSE_ADMIN_UNIT,
   MEDADMIN_ROUTE,
   MEDADMIN_SOURCE,
   RAW_MEDADMIN_MED_NAME,
   RAW_MEDADMIN_CODE,
   RAW_MEDADMIN_DOSE_ADMIN,
   RAW_MEDADMIN_DOSE_ADMIN_UNIT,
   RAW_MEDADMIN_ROUTE 
FROM MED_ADMIN JOIN N3C_COHORT ON MED_ADMIN.PATID = N3C_COHORT.PATID
WHERE MEDADMIN_START_DATE >= ADD_MONTHS(SYSDATE, -24);

--OBS_CLIN
SELECT
   OBSCLINID,
   OBS_CLIN.PATID,
   ENCOUNTERID,
   OBSCLIN_PROVIDERID,
   OBSCLIN_DATE,
   OBSCLIN_TIME,
   OBSCLIN_TYPE,
   OBSCLIN_CODE,
   OBSCLIN_RESULT_QUAL,
   OBSCLIN_RESULT_TEXT,
   OBSCLIN_RESULT_SNOMED,
   OBSCLIN_RESULT_NUM,
   OBSCLIN_RESULT_MODIFIER,
   OBSCLIN_RESULT_UNIT,
   OBSCLIN_SOURCE,
   RAW_OBSCLIN_NAME,
   RAW_OBSCLIN_CODE,
   RAW_OBSCLIN_TYPE,
   RAW_OBSCLIN_RESULT,
   RAW_OBSCLIN_MODIFIER,
   RAW_OBSCLIN_UNIT 
FROM OBS_CLIN JOIN N3C_COHORT ON OBS_CLIN.PATID = N3C_COHORT.PATID
WHERE OBSCLIN_DATE >= ADD_MONTHS(SYSDATE, -24);

--OBS_GEN
SELECT
   OBSGENID,
   OBS_GEN.PATID,
   ENCOUNTERID,
   OBSGEN_PROVIDERID,
   OBSGEN_DATE,
   OBSGEN_TIME,
   OBSGEN_TYPE,
   OBSGEN_CODE,
   OBSGEN_RESULT_QUAL,
   OBSGEN_RESULT_TEXT,
   OBSGEN_RESULT_NUM,
   OBSGEN_RESULT_MODIFIER,
   OBSGEN_RESULT_UNIT,
   OBSGEN_TABLE_MODIFIED,
   OBSGEN_ID_MODIFIED,
   OBSGEN_SOURCE,
   RAW_OBSGEN_NAME,
   RAW_OBSGEN_CODE,
   RAW_OBSGEN_TYPE,
   RAW_OBSGEN_RESULT,
   RAW_OBSGEN_UNIT 
FROM OBS_GEN JOIN N3C_COHORT ON OBS_GEN.PATID = N3C_COHORT.PATID
WHERE OBSGEN_DATE >= ADD_MONTHS(SYSDATE, -24);

--PRESCRIBING
SELECT
   PRESCRIBINGID,
   PRESCRIBING.PATID,
   ENCOUNTERID,
   RX_PROVIDERID,
   RX_ORDER_DATE,
   RX_ORDER_TIME,
   RX_START_DATE,
   RX_END_DATE,
   RX_DOSE_ORDERED,
   RX_DOSE_ORDERED_UNIT,
   RX_QUANTITY,
   RX_DOSE_FORM,
   RX_REFILLS,
   RX_DAYS_SUPPLY,
   RX_FREQUENCY,
   RX_PRN_FLAG,
   RX_ROUTE,
   RX_BASIS,
   RXNORM_CUI,
   RX_SOURCE,
   RX_DISPENSE_AS_WRITTEN,
   RAW_RX_MED_NAME,
   RAW_RX_FREQUENCY,
   RAW_RXNORM_CUI,
   RAW_RX_QUANTITY,
   RAW_RX_NDC,
   RAW_RX_DOSE_ORDERED,
   RAW_RX_DOSE_ORDERED_UNIT,
   RAW_RX_ROUTE,
   RAW_RX_REFILLS 
FROM PRESCRIBING JOIN N3C_COHORT ON PRESCRIBING.PATID = N3C_COHORT.PATID
WHERE RX_START_DATE >= ADD_MONTHS(SYSDATE, -24);

--PRO_CM
SELECT
   PRO_CM_ID,
   PRO_CM.PATID,
   ENCOUNTERID,
   PRO_DATE,
   PRO_TIME,
   PRO_TYPE,
   PRO_ITEM_NAME,
   PRO_ITEM_LOINC,
   PRO_RESPONSE_TEXT,
   PRO_RESPONSE_NUM,
   PRO_METHOD,
   PRO_MODE,
   PRO_CAT,
   PRO_SOURCE,
   PRO_ITEM_VERSION,
   PRO_MEASURE_NAME,
   PRO_MEASURE_SEQ,
   PRO_MEASURE_SCORE,
   PRO_MEASURE_THETA,
   PRO_MEASURE_SCALED_TSCORE,
   PRO_MEASURE_STANDARD_ERROR,
   PRO_MEASURE_COUNT_SCORED,
   PRO_MEASURE_LOINC,
   PRO_MEASURE_VERSION,
   PRO_ITEM_FULLNAME,
   PRO_ITEM_TEXT,
   PRO_MEASURE_FULLNAME 
FROM PRO_CM JOIN N3C_COHORT ON PRO_CM.PATID = N3C_COHORT.PATID
WHERE PRO_DATE >= ADD_MONTHS(SYSDATE, -24);

--PROCEDURES
SELECT
   PROCEDURESID,
   PROCEDURES.PATID,
   ENCOUNTERID,
   ENC_TYPE,
   ADMIT_DATE,
   PROVIDERID,
   PX_DATE,
   PX,
   PX_TYPE,
   PX_SOURCE,
   PPX,
   RAW_PX,
   RAW_PX_TYPE,
   RAW_PPX 
FROM PROCEDURES JOIN N3C_COHORT ON PROCEDURES.PATID = N3C_COHORT.PATID
WHERE PX_DATE >= ADD_MONTHS(SYSDATE, -24);

--PROVIDER
SELECT
   PROVIDERID,
   PROVIDER_SEX,
   PROVIDER_SPECIALTY_PRIMARY,
   PROVIDER_NPI,
   PROVIDER_NPI_FLAG,
   RAW_PROVIDER_SPECIALTY_PRIMARY 
FROM PROVIDER

--VITAL
SELECT
   VITALID,
   VITAL.PATID,
   ENCOUNTERID,
   MEASURE_DATE,
   MEASURE_TIME,
   VITAL_SOURCE,
   HT,
   WT,
   DIASTOLIC,
   SYSTOLIC,
   ORIGINAL_BMI,
   BP_POSITION,
   SMOKING,
   TOBACCO,
   TOBACCO_TYPE,
   RAW_DIASTOLIC,
   RAW_SYSTOLIC,
   RAW_BP_POSITION,
   RAW_SMOKING,
   RAW_TOBACCO,
   RAW_TOBACCO_TYPE 
FROM VITAL JOIN N3C_COHORT ON VITAL.PATID = N3C_COHORT.PATID
WHERE MEASURE_DATE >= ADD_MONTHS(SYSDATE, -24);

--PLACEHOLDER: SITE METADATA TABLE