
--DRUG_ERA
--OUTPUT_FILE: DRUG_ERA.csv
SELECT
   DRUG_ERA_ID,
   n.PERSON_ID,
   DRUG_CONCEPT_ID,
   CONVERT(VARCHAR(20),DRUG_ERA_START_DATE, 120) as DRUG_ERA_START_DATE,
   CONVERT(VARCHAR(20),DRUG_ERA_END_DATE, 120) as DRUG_ERA_END_DATE,
   DRUG_EXPOSURE_COUNT,
   GAP_DAYS
FROM @cdmDatabaseSchema.DRUG_ERA dre
JOIN @cohortDatabaseSchema.N3C_COHORT n
  ON DRE.PERSON_ID = N.PERSON_ID
WHERE DRUG_ERA_START_DATE >= '1/1/2018';
