
--OBSERVATION_PERIOD
--OUTPUT_FILE: OBSERVATION_PERIOD.csv
SELECT
   OBSERVATION_PERIOD_ID,
   p.PERSON_ID,
   CONVERT(VARCHAR(20),OBSERVATION_PERIOD_START_DATE, 120) as OBSERVATION_PERIOD_START_DATE,
   CONVERT(VARCHAR(20),OBSERVATION_PERIOD_END_DATE, 120) as OBSERVATION_PERIOD_END_DATE,
   PERIOD_TYPE_CONCEPT_ID
 FROM @cdmDatabaseSchema.OBSERVATION_PERIOD p
 JOIN @cohortDatabaseSchema.N3C_COHORT n
   ON p.PERSON_ID = n.PERSON_ID;
