
--VISIT_OCCURRENCE
--OUTPUT_FILE: VISIT_OCCURRENCE.csv
SELECT
   VISIT_OCCURRENCE_ID,
   n.PERSON_ID,
   VISIT_CONCEPT_ID,
   CONVERT(VARCHAR(20),VISIT_START_DATE, 120) as VISIT_START_DATE,
   CONVERT(VARCHAR(20),VISIT_START_DATETIME, 120) as VISIT_START_DATETIME,
   CONVERT(VARCHAR(20),VISIT_END_DATE, 120) as VISIT_END_DATE,
   CONVERT(VARCHAR(20),VISIT_END_DATETIME, 120) as VISIT_END_DATETIME,
   VISIT_TYPE_CONCEPT_ID,
   PROVIDER_ID,
   CARE_SITE_ID,
   VISIT_SOURCE_VALUE,
   VISIT_SOURCE_CONCEPT_ID,
   ADMITTING_SOURCE_CONCEPT_ID,
   ADMITTING_SOURCE_VALUE,
   DISCHARGE_TO_CONCEPT_ID,
   DISCHARGE_TO_SOURCE_VALUE,
   PRECEDING_VISIT_OCCURRENCE_ID
FROM @cdmDatabaseSchema.VISIT_OCCURRENCE v
JOIN @cohortDatabaseSchema.N3C_COHORT n
  ON v.PERSON_ID = n.PERSON_ID
WHERE v.VISIT_START_DATE >= '1/1/2018';
