
--DRUG_EXPOSURE
--OUTPUT_FILE: DRUG_EXPOSURE.csv
SELECT
   DRUG_EXPOSURE_ID,
   n.PERSON_ID,
   DRUG_CONCEPT_ID,
   CONVERT(VARCHAR(20),DRUG_EXPOSURE_START_DATE, 120) as DRUG_EXPOSURE_START_DATE,
   CONVERT(VARCHAR(20),DRUG_EXPOSURE_START_DATETIME, 120) as DRUG_EXPOSURE_START_DATETIME,
   CONVERT(VARCHAR(20),DRUG_EXPOSURE_END_DATE, 120) as DRUG_EXPOSURE_END_DATE,
   CONVERT(VARCHAR(20),DRUG_EXPOSURE_END_DATETIME, 120) as DRUG_EXPOSURE_END_DATETIME,
   DRUG_TYPE_CONCEPT_ID,
   STOP_REASON,
   REFILLS,
   QUANTITY,
   DAYS_SUPPLY,
   SIG,
   ROUTE_CONCEPT_ID,
   LOT_NUMBER,
   PROVIDER_ID,
   VISIT_OCCURRENCE_ID,
   null as VISIT_DETAIL_ID,
   DRUG_SOURCE_VALUE,
   DRUG_SOURCE_CONCEPT_ID,
   ROUTE_SOURCE_VALUE,
   DOSE_UNIT_SOURCE_VALUE
FROM @cdmDatabaseSchema.DRUG_EXPOSURE de
JOIN @cohortDatabaseSchema.N3C_COHORT n
  ON de.PERSON_ID = n.PERSON_ID
WHERE de.DRUG_EXPOSURE_START_DATE >= '1/1/2018';
