--DOSE_ERA
--OUTPUT_FILE: DOSE_ERA.csv

SELECT
   DOSE_ERA_ID,
   n.PERSON_ID,
   DRUG_CONCEPT_ID,
   UNIT_CONCEPT_ID,
   DOSE_VALUE,
   CONVERT(VARCHAR(20),DOSE_ERA_START_DATE, 120) as DOSE_ERA_START_DATE,
   CONVERT(VARCHAR(20),DOSE_ERA_END_DATE, 120) as DOSE_ERA_END_DATE
FROM @cdmDatabaseSchema.DOSE_ERA y JOIN @cohortDatabaseSchema.N3C_COHORT n ON y.PERSON_ID = N.PERSON_ID
WHERE y.DOSE_ERA_START_DATE >= '1/1/2018';
